apiVersion: apps/v1
kind: Deployment
metadata:
  name: mvn-web-app4-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mvn-web-app4
  template:
    metadata:
      labels:
        app: mvn-web-app4
    spec:
      containers:
      - name: mvn-web-app4-container
        image: IMAGE_NAME:TAG
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: springboot1secret
